package w05_OOMiddleware.HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* 12 October 2012 20:26:44 o'clock IST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
