package w05_OOMiddleware.HelloApp;

/**
* HelloApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* 12 October 2012 20:26:44 o'clock IST
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public w05_OOMiddleware.HelloApp.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (w05_OOMiddleware.HelloApp.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = w05_OOMiddleware.HelloApp.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
	  w05_OOMiddleware.HelloApp.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return w05_OOMiddleware.HelloApp.HelloHelper.type ();
  }

}
